apiVersion: v1
kind: Service
metadata:
  name: servicename
#  labels:
#    name: servicename
spec:
  type: NodePort
  clusterIP: string
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 8080
      protocol: tcp
  selector:
    name: servicename
