apiVersion: v1
kind: Pod
metadata:
  name: control_pod
  label: control_pod

spec:
  containers:
    - name: nginx1
      image: nginx:latest
      command:
      args:
      workingDir:

      ports:
        - name: http2
          containerPort: 80
          protocol: TCP

      resources:
        limits:
          cpu: 500m
          memory: 500Mi
