apiVersion: v1
kind: Pod
metadata:
  name: pod2-dns
  label: dns-test

spec:
  containers:
    - name: ghost3
      image: ghost
      command:
      args:
      workingDir:
      volumeMounts:
        - name: volume1
          mountPath: /vpath

      ports:
        - name: http1
          containerPort: 300
          protocol: TCP

    - name: nginx3
      image: nginx:latest
      command:
      args:
      workingDir:

      ports:
        - name: http2
          containerPort: 80
          protocol: TCP
