apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
spec:
  replicas: 6
  template:
    metadata:
      labels:
        name: test-service
    spec:
      containers:
        - name: nginx1
          image: nginx:latest
          command:
          args:
          workingDir:
          ports:
            - name: fileserver80
              containerPort: 80
              protocol: TCP
