apiVersion: v1
kind: Pod
metadata:
  name: pod_pre1
  label: test

spec:
  containers:
    - name: ghost3
      image: ghost
      command:
      args:
      workingDir:
      volumeMounts:
        - name: volume_test1
          mountPath: /vpath

      ports:
        - name: http1
          containerPort: 300
          protocol: TCP

      resources:
        limits:
          cpu: 500m
          memory: 500Mi

    - name: nginx3
      image: nginx:latest
      command:
      args:
      workingDir:
      volumeMounts:
        - name: volume_test1
          mountPath: /vpath

      ports:
        - name: http2
          containerPort: 80
          protocol: TCP

      resources:
        limits:
          cpu: 500m
          memory: 500Mi

  volumes:
    - name: volume_test1
      hostPath: /home/mount_test
