apiVersion: v1
kind: Pod
metadata:
  name: pod1
  label: test

spec:
  containers:
    - name: ghost3
      image: ghost
      command:
      args:
      workingDir:
      volumeMounts:
        - name: volume
          mountPath: /vpath

      ports:
        - name: http1
          containerPort: 300
          protocol: TCP

    - name: nginx3
      image: nginx:latest
      command:
      args:
      workingDir: /home/app/
      volumeMounts:
        - name: volume
          mountPath: /vpath

      ports:
        - name: http2
          containerPort: 80
          protocol: TCP

  volumes:
    - name: config
      hostPath: cpath
