apiVersion: v1
kind: Pod
metadata:
  name: pod2
  label: test
nodeSelector:
  with: pod1

spec:
  containers:
    - name: ghost3
      image: ghost
      command:
      args:
      workingDir:
      volumeMounts:
        - name: volume
          mountPath: /vpath

      ports:
        - name: http1
          containerPort: 320
          hostPort: 320
          protocol: TCP

    - name: nginx3
      image: nginx:latest
      command:
      args:
      workingDir: /home/app/
      volumeMounts:
        - name: volume
          mountPath: /vpath

      ports:
        - name: http2
          containerPort: 100
          hostPort: 100
          protocol: TCP

  volumes:
    - name: config
      hostPath: cpath
